### ISSUE TITLE
Missed info in Advanced settings of AdGuard for Android app

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/KnowledgeBase#102]
https://adguard.com/kb/adguard-for-mac/solving-problems/advanced-settings/
`Low-level settings` is a subsection of `Advanced settings` (wrong article name)
No info about the rest of settings

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/209529118-8a194142-3c30-435c-a4c3-1d6b8c250cd3.png)

</details>

**Comment by el-termikael** [comment]
the link leads to the article about AdGuard for Mac, it's correct in the one about AdGuard for Android: https://adguard.com/kb/adguard-for-android/solving-problems/low-level-settings/
