### ISSUE TITLE
Kb search often takes an excessive amount of time to show up

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/KnowledgeBase#142]
Sometimes it loads instantly when tapped, other times it takes up to ~10 seconds before it shows.

Showing search should really be a close to instantaneous action, consistently in this age of the internet.

https://user-images.githubusercontent.com/95468948/221133597-9c78a07f-1362-452b-b6bf-b98c0865e575.MOV

**Comment by ameshkov** [comment]
We are using a self hosted typesense for search, not sure this can easily be fixed.
