### ISSUE TITLE
Update Base filter URL

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/KnowledgeBase#18]
https://kb.adguard.com/en/general/adguard-ad-filters

From `https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_English/filter.txt` to `https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt`

**Comment by el-termikael** [comment]
@BlazDT hi, the URL in the Knowledge base is correct, please check it once again

**Comment by BlazDT** [comment]
Yes, meanwhile it is correct.
