### ISSUE TITLE
The links at the "Debugging scriptlets" section are dead

### ISSUE THREAD

**Issue by tumatanquang** [AdguardTeam/KnowledgeBase#195]
The scriptlet links at the [Debugging scriptlets](https://adguard.com/kb/general/ad-filtering/create-own-filters/#debug-scriptlets) section lead to the document all returning "404 - page not found".

**Comment by anastasiia-fedotova** [comment]
Hello! Thank you for reaching out. I've checked all the scriptlet links - they work properly now.

**Comment by anastasiia-fedotova** [comment]
Hello! Thank you for reaching out. I've checked all the scriptlet links - they work properly now.
