### ISSUE TITLE
Browser protected pages

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/KnowledgeBase#198]
@adguard-bot commented on [Fri May 19 2023](https://github.com/AdguardTeam/AdguardFilters/issues/151303)

### Issue URL (Social Widget)
 [https://addons.mozilla.org/blog/translate-the-web-easily-with-a-browser-extension/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Faddons.mozilla.org%2Fblog%2Ftranslate-the-web-easily-with-a-browser-extension%2F)
### Comment
Username: @spok1
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/DFhZdrN.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard Browser extension v4.1.55
Browser: | Firefox
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Strip URLs from tracking parameters, <br>Hide your Referrer from third-parties
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>AdGuard Ukrainian

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/KnowledgeBase/issues/199
