### ISSUE TITLE
Browser protected pages

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/KnowledgeBase#199]
Browser protected pages:

https://github.com/gorhill/uBlock/wiki/Privileged-Pages

I suggest write similar note in AdGuard KB.

Or steal idea from Stylus (promtped at top in pop-up "dashboard"): 

> 
![image](https://github.com/AdguardTeam/AdguardBrowserExtension/assets/35370833/cf2bc2ca-18a7-461a-b703-6f49a80ec091)

> Firefox forbids access to the site.
>
> To allow access open `about:config`, right-click the list, click 'New', then 'Boolean', paste `privacy.resistFingerprinting.block_mozAddonManager` and click OK, true, OK, reload the `addons.mozilla.org` page.
> * *(Чтобы разрешить доступ, перейдите на адрес `about:config`, нажмите правой кнопкой в списке, потом «Создать», потом «Логическое», вставьте текст `privacy.resistFingerprinting.block_mozAddonManager` и нажмите OK, <true>, OK, перезагрузите страницу `addons.mozilla.org`.)*
>
> In Firefox 60 and newer you need to remove this domain from `extensions.webextensions.restrictedDomains` in `about:config`.
> * *(В Firefox 60 и новее вам нужно удалить этот домен из `extensions.webextensions.restrictedDomains` в `about:config`.)*

Costs with use Stylus idea is broken button "remove extension" on webage addon description.

_Originally posted by @krystian3w in https://github.com/AdguardTeam/KnowledgeBase/issues/198#issuecomment-1576441558_

**Comment by krystian3w** [comment]
News:

https://mzl.la/3POXoWi

 >  **Run on sites with restrictions**
 >
 >  When allowed, the extension will have access to sites restricted by Mozilla. Allow only if you trust this extension
