### ISSUE TITLE
Empty code block in Safari HAR export instructions

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/KnowledgeBase#254]
@el-termikael, was the [empty code block](https://github.com/AdguardTeam/KnowledgeBase/blob/d8418db3d20872b65fb7bc1cbcd17d0591e64e45/docs/guides/collect-har-file.md?plain=1#L142)  in the Safari HAR export instructions intentional?

**Comment by el-termikael** [comment]
@jslawler no, it wasn't. already fixed it here: https://github.com/AdguardTeam/KnowledgeBase/pull/253
