### ISSUE TITLE
Blocking links from Firefox Pocket

### ISSUE THREAD

**Issue by Onigato** [AdguardTeam/KnowledgeBase#334]
After the most recent update AdGuard is blocking opening new tabs and new windows from the right click menu and straight click-through links from Pocket, but only for NSFW sites. Even other normally heavily ad-laden sites are able to be opened from Pocket, only NSFW sites appear to be blocked.

**Comment by anastasiia-fedotova** [comment]
Hello! It looks more like an issue than a suggestion to improve the knowledge base. Are you sure this information should be here and not in the product repository like this https://github.com/AdguardTeam/AdguardForWindows/issues?

**Comment by Onigato** [comment]
It's definitely intended to be an issue, not a knowledge-base article.
 

    On Tuesday, January 23, 2024 at 11:25:35 PM MST, Anastasiia Fedotova ***@***.***> wrote:  
 
 


Hello! It looks more like an issue than a suggestion to improve the knowledge base. Are you sure this information should be here and not in the product repository like this https://github.com/AdguardTeam/AdguardForWindows/issues?

**Comment by anastasiia-fedotova** [comment]
In this case, you should create an issue in the repository for the product in which you encountered the problem. I am closing this issue as it is not related to our knowledgebase.
