### ISSUE TITLE
Improve Safari Web extension article

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/KnowledgeBase#340]
1. go to Settings → Safari → Extensions
1. select "Ask" for AdGuard extension 
1. go to any website
1. Aa → AdGuard, and allow just for this particular website (not for every website)
1. do Aa → AdGuard again

as a result there will be `Limited permissions` shown in AdGuard Safari web extension popup:
https://uploads.adguard.org/slbdzdrvjk3ae.png

but this phrase—"Limited permissions"—is not mentioned in [the KB article](https://adguard.com/kb/adguard-for-ios/web-extension/) and there is no screenshot with such popup state. so the article may be improved because now it's not clear for a user is it a problem and how to deal with it

**Comment by anastasiia-fedotova** [comment]
related pull request -- https://github.com/AdguardTeam/KnowledgeBase/pull/413

**Comment by anastasiia-fedotova** [comment]
The article was updated
