### ISSUE TITLE
Make new screenshots for the AG for Mac Overview article

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/KnowledgeBase#368]
The article in Russian (https://adguard.com/kb/ru/adguard-for-mac/overview/) currently displays screenshots in English. We should add screenshots in Russian.

The screenshot under "Network" should also have the "Automatically filter applications" checkbox ticked, we need to upload a new one. This applies to the EN article too.

**Comment by DashaBu** [comment]
https://adguard.com/kb/ru/adguard-for-mac/overview/
