### ISSUE TITLE
Mandatory note about difference of the url-based and CSS-based rules

### ISSUE THREAD

**Issue by xdel** [AdguardTeam/KnowledgeBase#410]
I'm rarely composing my own rules and therefore tend to forget the right syntax/modifiers/whatever comes in the rule set. The 'create-own-filters' wiki page does not explicitly specify the difference between sets of rules mentioned in the topic, while most URL modifiers are invalid for CSS rules and may confuse beginner such as myself. I'd like to propose adding a note at the beginning of the CSS rules section stating that '||', '*' and other modifiers which URL blocker uses are incompatible with CSS rule syntax to avoid possible confusion such as creating CSS rule like '||domain.com##div...'.

**Comment by anastasiia-fedotova** [comment]
related pull request https://github.com/AdguardTeam/KnowledgeBase/pull/415
