### ISSUE TITLE
Change the way features overview is structured in the Knowledge base

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/KnowledgeBase#440]
Currently, we have a single HUGE article with the overview of ALL app features.

Example:
https://adguard.com/kb/adguard-for-android/overview/

Instead of that we should create may short articles that explain each feature separately.

For example, AdGuard for Android's `Features overview` should be split to several articles with the following structure:

* Features
    * Protection
        *  Ad blocking
        * Tracking protection
        * Annoyance blocking
        * Firewall
            * Quick actions
        * Browsing Security
    * Statistics
    * App management 
    * Settings
    * Assistant
    * Free vs full version
    * Rooted vs non-rooted devices
    * Integration with AdGuard VPN 

### Tasks list

* [ ] Android
* [ ] macOS
* [ ] Windows
* [ ] iOS
* [ ] Browser extension
* [ ] Safari
* [ ] Content blocker

**Comment by el-termikael** [comment]
done (AGM-1991)
