### ISSUE TITLE
Add an article about incompatibility of AdGuard for Mac with screen time

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/KnowledgeBase#465]
### Problem description:

1) Open AdGuard (default settings)
2) Go to system settings - Screen Time - Content&Privacy - Content Restrictions - Access to Web Content - Limit Adult Websites - 3) Customize then add example.org to Restricted sites
4) Open Safari

As a result, the connection fails and the pages do not load.

### Solution

The only solution is to disable Content&Privacy in Screen Time and reboot the system https://github.com/AdguardTeam/CoreLibs/issues/1790#issuecomment-1752447526.

**Comment by SeverAnna** [comment]
https://github.com/AdguardTeam/KnowledgeBase/pull/493

**Comment by SeverAnna** [comment]
https://github.com/AdguardTeam/KnowledgeBase/pull/493
