### ISSUE TITLE
Add description for `$inline-script` and `$inline-font`

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/KnowledgeBase#49]
check if they work similarly in [corelibs](https://github.com/AdguardTeam/CoreLibs/issues/1697) and [tsurlfilter](https://github.com/AdguardTeam/tsurlfilter/issues/68)

**Comment by ameshkov** [comment]
I guess in these cases we should explicitly mention that these rules are added for better compatibility with uBO and that internally they're converted into a different type of rules.
