### ISSUE TITLE
[zh-cn]: update the translation

### ISSUE THREAD

**Issue by tianyeeT** [AdguardTeam/KnowledgeBase#499]
- [ ] #498
- [ ] #500
- [ ] #501
- [ ] #502
- [ ] adguard-browser-extension/features/other-features.md
- [ ] adguard-browser-extension/features/stealth-mode.md
- [ ] adguard-browser-extension/solving-problems/logs.md
- [ ] adguard-browser-extension/availability.md
- [ ] adguard-browser-extension/comparison-standalone.md
- [ ] adguard-browser-extension/installation.md
- [ ] adguard-browser-extension/integration-mode.md
- [ ] adguard-browser-extension/overview.md
- [ ] adguard-browser-extension/protected-pages.md
- [ ] adguard-content-blocker/installation.md
- [ ] adguard-content-blocker/overview.md
- [ ] adguard-for-android/features/protection/firewall/firewall.md
- [ ] adguard-for-android/features/protection/firewall/quick-actions.md
- [ ] adguard-for-android/features/protection/ad-blocking.md
- [ ] adguard-for-android/features/protection/annoyance-blocking.md
- [ ] adguard-for-android/features/protection/browsing-security.md
- [ ] adguard-for-android/features/protection/dns-protection.md
- [ ] adguard-for-android/features/protection/tracking-protection.md
- [ ] adguard-for-android/features/app-management.md
- [ ] adguard-for-android/features/assistant.md
- [ ] adguard-for-android/features/free-vs-full.md
- [ ] adguard-for-android/features/integration-with-vpn.md
- [ ] adguard-for-android/features/rooted.md
- [ ] adguard-for-android/features/settings.md
- [ ] adguard-for-android/features/statistics.md
- [ ] adguard-for-android/solving-problems/adguard-for-android-tv.md
- [ ] adguard-for-android/solving-problems/adguard-outbound-proxy.md
- [ ] adguard-for-android/solving-problems/background-work.md
- [ ] adguard-for-android/solving-problems/battery.md
- [ ] adguard-for-android/solving-problems/compatibility-issues.md
- [ ] adguard-for-android/solving-problems/firefox-certificates.md
- [ ] adguard-for-android/solving-problems/har.md
- [ ] adguard-for-android/solving-problems/https-certificate-for-rooted.md
- [ ] adguard-for-android/solving-problems/log.md
- [ ] adguard-for-android/solving-problems/logcat.md
- [ ] adguard-for-android/solving-problems/low-level-settings.md
- [ ] adguard-for-android/solving-problems/manual-certificate.md
- [ ] adguard-for-android/solving-problems/multiple-profiles-issue.md
- [ ] adguard-for-android/solving-problems/multiple-user-profiles.md
- [ ] adguard-for-android/solving-problems/outbound-proxy.md
- [ ] adguard-for-android/solving-problems/restricted-profile.md
- [ ] adguard-for-android/solving-problems/samsungpay-with-adguard-in-south-korea.md
- [ ] adguard-for-android/solving-problems/secure-folder.md
- [ ] adguard-for-android/solving-problems/tasker.md
- [ ] adguard-for-android/solving-problems/youtube-ads.md
- [ ] adguard-for-android/installation.md
- [ ] adguard-for-android/overview.md
- [ ] adguard-for-ios/features/activity.md
- [ ] adguard-for-ios/features/advanced-protection.md
- [ ] adguard-for-ios/features/assistant.md
- [ ] adguard-for-ios/features/compatibility-with-adguard-vpn.md
- [ ] adguard-for-ios/features/dns-protection.md
- [ ] adguard-for-ios/features/low-level-settings.md
- [ ] adguard-for-ios/features/other-features.md
- [ ] adguard-for-ios/features/safari-protection.md

**Comment by DashaBu** [comment]
@tianyeeT Thank you for your translation! Next time you can offer the translation in [Crowdin](https://crowdin.com/project/adguard-knowledge-base/zh-CN). We do not use GitHub to translate the Knowledge Base articles. [Here](https://adguard.com/kb/zh-CN/miscellaneous/contribute/translate/become-translator/) you can find more information about the platform.
