### ISSUE TITLE
Update sources section in the userscripts article

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/KnowledgeBase#535]
I am talking about this section: https://adguard.com/kb/general/userscripts/#more-userscripts

1. Stylish no more allows conversion to userscripts so this source needs to be removed
2. Add a link to userscript.zone

In general, here's how Tampermonkey explains where to get userscripts:
![image](https://github.com/user-attachments/assets/38f751bb-4853-4816-98c6-f5ff8344b6ac)

**Comment by puglieri** [comment]
Pull request: https://github.com/AdguardTeam/KnowledgeBase/pull/540
