### ISSUE TITLE
Update `How to use AdGuard with NordVPN` article

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/KnowledgeBase#536]
https://adguard.com/kb/adguard-for-android/solving-problems/outbound-proxy/#how-to-use-adguard-with-nordvpn

The current workflow for adding a server is incorrect.

Instead of using users' NordVPN account credentials, you need to 

- Go to your NordVPN account
- Set up NordVPN manually
- Receive a verification code in your email that you use for NordVPN services. Type the code in
- Click Apply and OK to save changes
- Use these credentials in AdGuard: 

![image](https://github.com/user-attachments/assets/dd79671e-7563-40b4-8c11-96d60cdb7c45)

Article for reference: https://support.nordvpn.com/hc/en-us/articles/19449763497489-NordVPN-proxy-setup-for-uTorrent

**Comment by puglieri** [comment]
Pull request: https://github.com/AdguardTeam/KnowledgeBase/pull/538
