### ISSUE TITLE
Add short "Overview" articles to every product section

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/KnowledgeBase#579]
Currently, there's no place that describes (at least very briefly) what the product is or where to get it from.

I suggest adding a very short "Overview" article to every product section.

This article should be the entry point, i.e. when I click on "AdGuard for Windows" in the left sidebar navigation, it should lead me to the overview article.

The article structure should be simple:

1. Short product description
2. Overview of the KB content (with links to them).

**Comment by SeverAnna** [comment]
https://github.com/AdguardTeam/KnowledgeBase/pull/590
