### ISSUE TITLE
Feature Request: Documentation on Request Filtering in AdGuard

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/KnowledgeBase#594]
**Description:**
A user on Telegram had an issue where GQUIC is blocked by AdGuard with no explanation as to why given under "Applied rules".
This is not documented.

To enhance user understanding and transparency, it would be beneficial for the AdGuard knowledge base to include detailed documentation regarding how various requests are handled, specifically those that are blocked, allowed, or modified with no explanation as to why given.

**Request Types:**

1. **Blocked Requests:** Please provide a list of request types or domains that AdGuard blocks by default.

2. **Allowed Requests:** Identify specific types of requests that are permitted without any modifications.

3. **Modified Requests:** Clarify which requests are modified by AdGuard, along with explanations of the changes made.

The above should also be handled by the AdGuard apps as it's not currently a good design showing that something is blocked with no obvious reason why.

**Comment by vyanovsky** [comment]
Added basic documentation here: https://github.com/AdguardTeam/KnowledgeBase/pull/613
