### ISSUE TITLE
Replace microShield userscript with tinyShield

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/KnowledgeBase#604]
I believe that [tinyShield userscript](https://github.com/List-KR/tinyShield) is a next-generation userscript for preventing Ad-Shield's reinserted advertisement.
Because it does block recovery code of Ad-Shield instead of blocking all methods of Ad-Shield script. Therefore, currently the userscript does not fall over `try...catch` trap of Ad-Shield.

It does not based on any project unlike microShield does.

**Comment by el-termikael** [comment]
closed in #614
