### ISSUE TITLE
Remove "Technical support" page from KB

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/KnowledgeBase#74]
Talking about this:
https://adguard.com/kb/support/contact/

It duplicates the page that we already have:
https://adguard.com/en/support.html

**Comment by ameshkov** [comment]
It is already mentioned in the footer, what's the point of having it in two places?

**Comment by el-termikael** [comment]
Alright then: https://github.com/AdguardTeam/KnowledgeBase/pull/90
