### ISSUE TITLE
Add an article about Samsung Pay app in Korea

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/KnowledgeBase#80]
The original content is here:
[How to use Samsung Pay with AdGuard in South Korea](https://kb.adguard.com/en/android/solving-problems/samsungpay-with-adguard-in-south-korea)

Currently, this article is missing from the new KB.

**Comment by el-termikael** [comment]
This article is partially in Korean. We need to translate it in English and to mention that the problem mostly concerns Korean users.

**Comment by el-termikael** [comment]
@NataKiss please translate the Korean pieces
you can commit to the same branch as @DashaBu did:
https://github.com/AdguardTeam/KnowledgeBase/pull/100

**Comment by el-termikael** [comment]
It turned out that the pieces of text in Korean mean the same as the English part so we can remove them without a doubt.

**Comment by el-termikael** [comment]
https://github.com/AdguardTeam/KnowledgeBase/pull/100
