### ISSUE TITLE
Add an article about Proxy certificate installation

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/KnowledgeBase#82]
This article is missing from the new KB:
https://kb.adguard.com/en/technical-support/how-to-install-certificate

I suggest placing it under `General->HTTPS filtering`.

Android section should mention that the apps do not trust user certs by default.

**Comment by el-termikael** [comment]
This article is already present in the new Knowledge base: https://adguard.com/kb/guides/proxy-certificate/. It has been updated and expanded so now there are proper instructions for Android, iOS, Windows, and Mac.

> Android section should mention that the apps do not trust user certs by default.
Isn't it true for iOS?

**Comment by ameshkov** [comment]
Nope, that's only true for Android. It means that HTTPS can only be filtered in Android browsers, but not apps.

**Comment by el-termikael** [comment]
@ameshkov please check https://github.com/AdguardTeam/KnowledgeBase/pull/108
