### ISSUE TITLE
Adware and Viruses article is outdated

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/KnowledgeBase#86]
[The article ](https://adguard.com/kb/guides/adware/) is outdated.

Here's the list of issues with it:

1. Kaspersky tool links to a Ru website
2. There are more free scanning tools, why don't we recommend them?
3. "Free antivirus utilities" should be a header so that it was in the TOC
4. "How to remove ...." sections are outdated, these types of adware are not used anymore so this all can be safely removed

**Comment by el-termikael** [comment]
https://github.com/AdguardTeam/KnowledgeBase/pull/95
